---
name: Dennis
surname: Murithi
position: "Student"
address: "Nairobi"
phone: +254 703 431 748
profilepic: "C:/Users/adm/Pictures/Saved Pictures/DSC_9385 (2).jpg"
email: "dennisaltegaz@gmail.com"
twitter: dennisdennis
github: dennisaltegaz174
linkedin: dennisaltegaz174
date: "`r format(Sys.time(), '%B %Y')`"
aboutme: "I have been doing data science  in a variety of languages for over 2+ years. I have a deep driven passion for machine learning / artificial inteligence, automation, and data science."
output: vitae::twentyseconds
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Applied Statistics with computing", "2007 – 2021", "Moi University", "Eldoret, Kenya",
  "Kenya Certificate of Secondary Education", "2014-2017", "High school ", "xyz, Kenya",
  "Kenya Certificate of Primary Education", "1999-2013", " Lighthouse Academy", "Nairobi, Kenya"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Work Experience

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Informal studies", "2001 - 2011", "Flying University", "Warsaw, kisumu",
  "Master of Physics", "2012-2013", "kibabii University", "nairobi, France",
  "Master of Mathematics", "2017-109", "kenyatta University", "Nairobi, France"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Skills

```{r}
library(tibble)
skills <- tribble(
 ~ Degree, ~ skills,
  "Programming Languages","Python, R, T-SQL, PL-SQL",
  "Markup Languages", " HTML, LaTeX, Markdown, RMarkdown",
  "Other Languages", "YAML",
  "Version Control", "Git",
  "Text Editors", "RStudio,VIM, Visual Studio, Visual Studio Code",
  "Microsoft Office", "Excel, Outlook, PowerBI, PowerPoint, Word"
) %>% 
    detailed_entries(Degree, skills)
```
  
  
# Honours

```{r}
honors <- tribble(
  ~area, ~accomplishment, ~year, ~where, ~detail,
  "Phi Theta Kappa Academic Honor Society", "Granted to individuals in the 90th percentile of their graduating class", 2015, "Cosumnes River College",NA,
  "Galt Community Character Coalition Honesty Award", "Awarded by the Galt City Council", 2010, "City Of Galt",NA
)%>%
  detailed_entries(
    with = area,
    what = accomplishment,
    why = detail,
    when = year,
    where = where
  )
```

  
  
# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

